server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: app
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: root
    password:
    validation-query: SELECT 1
  h2:
    console:
      enabled: true
